import subprocess
import sys
from pathlib import Path

from fastapi.testclient import TestClient

from app.api import create_api
from app.schemas.plan import ImplementationPlan, PlanStep
from app.schemas.review import ReviewReport


class FakeLLMClient:
    def generate_text(self, prompt: str) -> str:
        return "# LLM API Report\n\n## Risk assessment\nAPI-routed report."

    def generate_structured(self, prompt: str, schema: type) -> object:
        if schema is ImplementationPlan:
            return ImplementationPlan(
                task="Add request logging middleware",
                summary="API-routed LLM plan.",
                steps=[
                    PlanStep(
                        id=1,
                        title="Plan middleware",
                        description="Plan a request logging middleware change.",
                    )
                ],
                acceptance_criteria=["Plan is generated by the injected LLM client."],
                tests_to_run=["python -m pytest -q"],
            )
        if schema is ReviewReport:
            return ReviewReport(summary="API-routed LLM review.", findings=[])
        raise AssertionError(f"Unexpected schema: {schema}")


def test_api_creates_and_fetches_run(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr("app.api.settings.llm_provider", "mock")
    client = TestClient(create_api(storage_path=tmp_path / "runs.db"))

    response = client.post(
        "/runs",
        json={
            "repo_path": "examples/sample_fastapi_app",
            "task": "Add request logging middleware",
        },
    )

    assert response.status_code == 201
    run_id = response.json()["run_id"]

    run_response = client.get(f"/runs/{run_id}")
    report_response = client.get(f"/runs/{run_id}/report")
    logs_response = client.get(f"/runs/{run_id}/logs")

    assert run_response.status_code == 200
    assert run_response.json()["run_id"] == run_id
    assert "Risk assessment" in report_response.json()["report"]
    assert logs_response.json()["logs"][0] == "scan_repo:start"


def test_api_handoff_formats(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr("app.api.settings.llm_provider", "mock")
    client = TestClient(create_api(storage_path=tmp_path / "runs.db"))

    created = client.post(
        "/runs",
        json={"repo_path": "examples/sample_fastapi_app", "task": "Exercise handoff routes"},
    )
    run_id = created.json()["run_id"]

    markdown_response = client.get(f"/runs/{run_id}/handoff")
    assert markdown_response.status_code == 200
    assert markdown_response.headers["content-type"].startswith("text/markdown")
    assert "Worker handoff packet" in markdown_response.text

    json_response = client.get(f"/runs/{run_id}/handoff", params={"format": "json"})
    assert json_response.status_code == 200
    envelope = json_response.json()
    assert envelope["verification_commands"]
    assert envelope["markdown"].startswith("# Worker")


def test_api_returns_404_for_missing_run(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr("app.api.settings.llm_provider", "mock")
    client = TestClient(create_api(storage_path=tmp_path / "runs.db"))

    response = client.get("/runs/missing")

    assert response.status_code == 404


def test_api_routes_injected_llm_client(tmp_path: Path) -> None:
    client = TestClient(create_api(storage_path=tmp_path / "runs.db", llm_client=FakeLLMClient()))

    response = client.post(
        "/runs",
        json={
            "repo_path": "examples/sample_fastapi_app",
            "task": "Add request logging middleware",
        },
    )

    run_id = response.json()["run_id"]
    run_response = client.get(f"/runs/{run_id}")

    assert run_response.json()["plan"]["summary"] == "API-routed LLM plan."
    assert run_response.json()["review_report"]["summary"] == "API-routed LLM review."


def test_api_can_create_edit_mode_run(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr("app.api.settings.llm_provider", "mock")
    repo_path = tmp_path / "repo"
    repo_path.mkdir()
    (repo_path / "app.py").write_text("print('hello')\n")
    subprocess.run(["git", "init"], cwd=repo_path, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo_path, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo_path, check=True)
    subprocess.run(["git", "add", "."], cwd=repo_path, check=True)
    subprocess.run(
        ["git", "commit", "-m", "initial"],
        cwd=repo_path,
        check=True,
        capture_output=True,
    )
    worker_path = tmp_path / "worker.py"
    worker_path.write_text(
        "from pathlib import Path\n"
        "Path('marker.txt').write_text('created\\n')\n"
        "print('api worker complete')\n"
    )
    client = TestClient(create_api(storage_path=tmp_path / "runs.db"))

    response = client.post(
        "/runs",
        json={
            "repo_path": str(repo_path),
            "task": "Create marker",
            "worker_command": f"{sys.executable} {worker_path}",
            "test_commands": [],
        },
    )

    assert response.status_code == 201
    run_response = client.get(f"/runs/{response.json()['run_id']}")
    payload = run_response.json()
    assert payload["edit_result"]["status"] == "completed"
    assert "marker.txt" in payload["changed_files"]
